services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tablefootball
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: /usr/bin/pg_isready -U user -d tablefootball
      interval: 5s
      timeout: 10s
      retries: 120
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    build: .
    image: 192.168.1.101:5000/test-football:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8030:8030"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/tablefootball

volumes:
  postgres-data:
